apiVersion: v1
kind: Service
metadata:
  name: parlay-analyzer
spec:
  type: {{ .Values.service.type }}
  selector:
    app: parlay-analyzer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
